ckpt_path: /path/to/ckpt # used for testing only, add your ckpt path if you want to test the model
# weight_init: /path/to/weight_init # if you want to finetune va-vae on your own dataset, add your weight_init path

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 3 #32
    # hyper-param for vision foundation model alignment
    # --------------------------------------------------
    use_vf: dinov2_small #dinov2
    reverse_proj: true        # default: true, project from vae dim --> dinov2 dim
    # --------------------------------------------------
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 5001
        kl_weight: 1.0e-06
        disc_weight: 0.5
        # hyper-param for vision foundation model alignment
        # --------------------------------------------------
        vf_weight: 0.1
        adaptive_vf: true
        distmat_margin: 0.25
        cos_margin: 0.5
        # --------------------------------------------------
    ddconfig:
      double_z: true
      z_channels: 3 #32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1 #8 # batch size per GPU
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
#        data_root: /mnt/HDD2/dataset/imagenet #d26
#        data_root: /mnt/SSD_raid1/imagenet/ # navi
        data_root: /mnt/HDD2/dataset/cifar-100/train # d26
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
#        data_root: /mnt/HDD2/dataset/imagenet #d26
#        data_root: /mnt/SSD_raid1/imagenet/ # navi
        data_root: /mnt/HDD2/dataset/cifar-100/val # d26

lightning:
  trainer:
    devices: 1 #8 # number of GPUs, modify it according to your settings
    num_nodes: 1 #4 # number of nodes, modify it according to your settings # number of machines
    strategy: ddp_find_unused_parameters_true
    accelerator: gpu
    max_epochs: 20 #50
    precision: 32