#ckpt_path: "../pretrained_weight/vavae-imagenet256-f16d32-dinov2.pt" # used for testing only, add your ckpt path if you want to test the model
#init_weight: "../pretrained_weight/vavae-imagenet256-f16d32-dinov2.pt" # if you want to finetune va-vae on your own dataset, add your weight_init path
init_weight: "logs/3rd_2025-08-14T23-49-32_f16d32_vfdinov2/checkpoints/model-step=20000.ckpt"
init_weight2: "vavae-imagenet256-f16d32-dinov2.pt"

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    # hyper-param for vision foundation model alignment
    # --------------------------------------------------
    use_vf: dinov2
    reverse_proj: true        # default: true, project from vae dim --> dinov2 dim
    # --------------------------------------------------
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 40001 # 5001 # 1 for ckpt continued training
        kl_weight: 1.0e-06
        disc_weight: 0.5
        # hyper-param for vision foundation model alignment
        # --------------------------------------------------
        vf_weight: 0.1
        adaptive_vf: true
        distmat_margin: 0.25
        cos_margin: 0.5
        # --------------------------------------------------
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4 # batch size per GPU
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: /mnt/SSD_raid1/imagenet #/path/to/imagenet
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        data_root: /mnt/SSD_raid1/imagenet #/path/to/imagenet

lightning:
  trainer:
    devices: 4 #8 # number of GPUs, modify it according to your settings
    num_nodes: 1 #4 # number of nodes, modify it according to your settings
    strategy: ddp_find_unused_parameters_true
    accelerator: gpu
    max_epochs: 20 #50
    precision: 32